#source("http://bioconductor.org/biocLite.R");
#biocLite("affy");
#biocLite("affyPLM");
#biocLite("org.Dm.eg.db");
library(affy);
library(affyPLM);
library(org.Dm.eg.db);
rawProbeData <- ReadAffy();
#probeValues <- exprs(rawProbeData);
#probeNames <- probeNames(rawProbeData);
expressionSet <- rma(rawProbeData);
probesets <- featureNames(expressionSet);
samples <- sampleNames(expressionSet);
expressionMatrix <- exprs(expressionSet);