#source("http://bioconductor.org/biocLite.R");
#biocLite("affy");
#biocLite("affyPLM");
#biocLite("org.Dm.eg.db");
library(affy);
library(affyPLM);
library(org.Dm.eg.db);
ourdata <- ReadAffy();
values <- exprs(ourdata);
probes <- featureNames(ourdata);
samples <- sampleNames(ourdata);
